### ISSUE TITLE
the pretrained resenet model under shapenet

### ISSUE THREAD

**Issue by takeshie** [ThibaultGROUEIX/AtlasNet#76] opened 2022-09-08 01:56 UTC
hi,friend,your work is really charming, I want to follow this project. could you release the pretrained resenet model under shapenet?

**Comment by ThibaultGROUEIX** [comment] 2022-10-05 23:59
Hi, It is released in the README.md.
Maybe i did not understand your question?

**Comment by ThibaultGROUEIX** [comment] 2023-03-03 04:21
Closing this since the issue is stale, feel free to reopen. Thanks a lot for for playing around with AtlasNet.
Cheers,
Thibault

**Closed as completed by ThibaultGROUEIX** 2023-03-03 04:21 UTC
